### ISSUE TITLE
Trouble Building 

### ISSUE THREAD

**Issue by david0rk** [TEAMarg/ID-40-VIRUS-LQP-79#5]
C:\Users\david0rk\Documents\Arduino\libraries\Arduboy2\src\Arduboy2.cpp:174:18: error: 'MUX5' was not declared in this scope
     ADCSRB = _BV(MUX5);
                  ^
I've never done much with an arduino, but this looks like a missing include,  any specific version of the arduboy or arduboy2 libs required to build this?

**Comment by david0rk** [comment]
I'm an idiot, didn't add install the arduboy in the board manager. builds fine now.

**Comment by JO3RI** [comment]
😀
