### ISSUE TITLE
Victory Screen

### ISSUE THREAD

**Issue by Chirishman** [TEAMarg/ID-40-VIRUS-LQP-79#6]
Feature Request: Victory screen and/or sound.

Not sure if I was mashing A and missed something but after completing level 60something (wasn't paying attention to the level numbers at that point honestly) I got dumped back to the game's starting menu.

If that was in fact the end I would have expected a little more fanfare or a screen with my score to take a picture of. Maybe require a power cycle to clear the "Game Cleared" message?

**Comment by JO3RI** [comment]
When this game was created, we didn't have room enough to add an ending screen. You have to realize 32 kb isn't very much.

Now the main Arduboy library has been made a bit smaller, so we could add an ending screen and maybe extra levels.

There are 64 levels in total.

When we have time, we'll look into this.

**Comment by Chirishman** [comment]
Addressed in commit ee27c52fb2828aa3b5adfb9fa2bb8fe2e1a1bbf6
